title: Getting started with Arduino compatible micro-controllers
hero_image: images/banner.png
description: getting-started-arduino description
version: 4
listed: false
copyedit: false
last_tested: "2018-06-29"
steps:
  - title: Introduction
  - title: What you will need
  - title: Introduction to Arduino
  - title: The Arduino IDE
  - title: The "Hello World" first Arduino sketch
  - title: Two LEDs on a breadboard
